# Generated by Django 5.1.2 on 2024-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_study_time',
            field=models.IntegerField(default=0),
        ),
    ]
